language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install pipenv
  - pipenv install
script:
  - python setup.py sdist bdist_wheel --universal
branches:
  only:
    - master

